### ISSUE TITLE
Logo, background and name

### ISSUE THREAD

**Issue by kavishme** [jayakirtani/cmpe281-shopping-cart#24]

**Comment by kavishme** [comment]
Name - PetInc
Logo and Background image: @Waad-DB 
![icon64](https://cloud.githubusercontent.com/assets/12120443/14519420/961e4044-01d3-11e6-87c7-9850b3b21f44.png)
![bigstock-group-of-pets-dog-cat-bird-44783536](https://cloud.githubusercontent.com/assets/12120443/14519422/98c12672-01d3-11e6-9eae-1957b82a00d2.jpg)

**Comment by kavishme** [comment]
Image for welcome cum login page. Made icon in  multiple sizes 16_16, 32_32, 64_64, 128_128

**Comment by kavishme** [comment]
@jayakirtani @Imran-syed @Naraharibharathkumar

**Comment by Imran-syed** [comment]
yep, seems good to me.

**Comment by WaadAljaradt** [comment]
I like the logo ! not sure about the images

**Comment by WaadAljaradt** [comment]
i rather have 4 images of pets and food

**Comment by WaadAljaradt** [comment]
could you send me the logo i want to add it in the welcome page @kavishme

**Comment by WaadAljaradt** [comment]
take a look at these pictures, and add pictures there as well in the future 

https://drive.google.com/a/sjsu.edu/folderview?id=0B-IqZqtGQ506Nlc2VmRfaW5uWjQ&usp=sharing

**Comment by kavishme** [comment]
Logo decided, and background images provided by Waad seems good.
