### ISSUE TITLE
Express modules for session and authentication

### ISSUE THREAD

**Issue by kavishme** [jayakirtani/cmpe281-shopping-cart#31]
We need to select some express modules for easy sessions management and authentication

**Comment by kavishme** [comment]
TO: @jayakirtani @Naraharibharathkumar @Imran-syed @syedimran-ahmed 
CC: @Waad-DB 

Found this very good tutorial on full mean stack development.
https://mva.microsoft.com/en-US/training-courses/mean-stack-jump-start-8442?l=eovSb3Vz_4604984382

Guys I suggest to use modules passport (for authentication), express-session (session management) and bcrypt (hashing) for backend development. 
@jayakirtani this vids also make clear API required for authentication.

**Comment by WaadAljaradt** [comment]
yes using these modules will make it easier for us to manage sessions and password encryption

**Comment by kavishme** [comment]
using passport for authentication and express-session for session management
